name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .
      - run: nix run . &
      - uses: grossamos/rudra@v0.1.2
        name: init rudra
        with:
          stage: "preperation"
          openapi-source: "docs/swagger.json"
          instance-url: "http://localhost:8080"
          account-for-security: false
          test-coverage: "90%"
          only-account-for-pr: true
          #services: |
             #http://localhost:8080; docs/swagger.yaml; 13750;
      - uses: matt-ball/newman-action@master
        name: run integration tests
        with:
          collection: tests/rudra-example.postman_collection.json
          environment: tests/rudra-example-ci.postman_environment.json
      - uses: grossamos/rudra@v0.1.2
        name: eval rudra
        with:
          stage: "evaluation"
