name: Integration Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nix
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build .
      - run: nix run . &
      - uses: grossamos/rudra@v0.1.0
        name: init rudra
        with:
          stage: "preperation"
          openapi-source: "docs/swagger.json"
          instance-url: "http://localhost:8080"
          account-for-security: false
          test-coverage: "90%"
            # mapping: |
            # https://localhost:8090; docs/swagger1.yaml; 13751;
            # https://example:8091; docs/swagger2.yaml; 13752;
      - uses: matt-ball/newman-action@master
        name: run integration tests
        with:
          collection: tests/rudra-example.postman_collection.json
          environment: tests/rudra-example-ci.postman_environment.json
      - uses: grossamos/rudra@v0.1.0
        name: eval rudra
        with:
          stage: "evaluation"
