name: Integration Tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: export NIXPKGS_ALLOW_UNFREE=1
      - run: nix-shell --run "go run main.go &"
      - uses: matt-ball/newman-action@master
        with:
          collection: tests/rudra-example.postman_collection.json
