name: Integration Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: export NIXPKGS_ALLOW_UNFREE=1 && nix-shell --run "go build"
      - run: ./rudra-example &
      - uses: grossamos/rudra@v0.0.3-alpha.4
        with:
          stage: "preperation"
          openapi-path: "docs/swagger.json"
          instance-url: "http://localhost:8080"
          account-for-security: false
      - uses: matt-ball/newman-action@master
        with:
          collection: tests/rudra-example.postman_collection.json
          environment: tests/rudra-example-ci.postman_environment.json
      - uses: grossamos/rudra@v0.0.3-alpha.4
        with:
          stage: "evaluation"
